name: sharing_map
description: Sharing map application

version: 0.1.8+1

environment:
  sdk: ">3.3.0 <4.0.0"

dependencies:
  flutter:
    sdk: flutter
  flutter_svg: ^2.0.5
  introduction_screen: ^3.1.8
  go_router: ^14.2.7
  http_interceptor: ^2.0.0-beta.8
  dio: ^5.3.3

  flutter_launcher_icons: ^0.14.1
  provider: ^6.0.5

  carousel_slider: ^5.0.0
  image_picker: ^1.1.2
  shared_preferences: ^2.3.4
  aws_signature_v4: ^0.6.3
  permission_handler: ^11.3.0
  get: ^4.6.5
  http: ^1.2.1
  uuid: ^4.3.3
  flutter_dotenv: ^5.1.0
  cached_network_image: ^3.3.0
  email_validator: ^3.0.0
  jwt_decoder: ^2.0.1
  flutter_verification_code: ^1.1.7
  infinite_scroll_pagination: ^4.0.0
  intl: ^0.20.1
  dropdown_search: ^6.0.1
  font_awesome_flutter: ^10.6.0
  url_launcher: ^6.3.1
  flutter_native_splash: ^2.3.10
  flutter_secure_storage: ^10.0.0-beta.4
  flutter_image_compress: ^2.1.0
  flutter_cache_manager: ^3.3.1
  dropdown_button2: ^2.3.9

  aws_common: ^0.7.3
  url_strategy: ^0.3.0
  auto_size_text: ^3.0.0
  geolocator: ^13.0.2
flutter_launcher_icons:
  android: true
  ios: true
  image_path: "assets/images/sm_logo_green.png"
  min_sdk_android: 21 # android min sdk min:16, default 21
  web:
    generate: true
    image_path: "assets/images/sm_logo_green.png"
    background_color: "#hexcode"
    theme_color: "#hexcode"
  windows:
    generate: true
    image_path: "assets/images/sm_logo_green.png"
    icon_size: 48 # min:48, max:256, default: 48
  macos:
    generate: true
    image_path: "assets/images/sm_logo_green.png"
dev_dependencies:
  flutter_test:
    sdk: flutter
  change_app_package_name: ^1.1.0

flutter:
  uses-material-design: true


  assets:
    - assets/images/
    - assets/icons/
    - assets/images/intro/
    - assets/images/categories/
    - assets/fonts/
    - env/
  fonts:
   - family: Roboto
     fonts:
       - asset: assets/fonts/Roboto-Black.ttf
         weight: 900
       - asset: assets/fonts/Roboto-BlackItalic.ttf
         weight: 900
         style: italic
       - asset: assets/fonts/Roboto-Medium.ttf
         weight: 600
       - asset: assets/fonts/Roboto-MediumItalic.ttf
         weight: 600
         style: italic
