name: sharing_map
description: Pet Shop is an e-commerce application for Android built with Flutter (iOS to come soon).

# The following defines the version and build number for your application.
# A version number is three numbers separated by dots, like 1.2.43
# followed by an optional build number separated by a +.
# Both the version and the builder number may be overridden in flutter
# build by specifying --build-name and --build-number, respectively.
# In Android, build-name is used as versionName while build-number used as versionCode.
# Read more about Android versioning at https://developer.android.com/studio/publish/versioning
# In iOS, build-name is used as CFBundleShortVersionString while build-number used as CFBundleVersion.
# Read more about iOS versioning at
# https://developer.apple.com/library/archive/documentation/General/Reference/InfoPlistKeyReference/Articles/CoreFoundationKeys.html
version: 1.0.0+3

environment:
  sdk: ">2.17.0 <4.0.0"

dependencies:
  flutter:
    sdk: flutter
  flutter_svg: ^2.0.5
  introduction_screen: ^3.1.8
  go_router: ^8.0.5
  http_interceptor: ^1.0.1
  dio: ^5.3.3
  #firebase services
  # firebase_auth: ^4.6.0
  # cloud_firestore: ^4.7.0
  # firebase_messaging: ^14.6.0
  # firebase_core: ^2.12.0
  # firebase_storage: ^11.2.0

  #google and other stuff
  flutter_launcher_icons: ^0.13.1
  google_fonts:
  wc_flutter_share: ^0.4.0
  provider: ^6.0.5

  #image processing magic
  carousel_slider: ^4.2.1
  image_cropper: ^3.0.3
  flutter_spinkit: "^5.2.0"
  image_picker: ^1.0.1
  photo_view: ^0.14.0
  shared_preferences: ^2.2.1
  path: ^1.6.4
  aws_signature_v4: ^0.5.0
  #location and permission handling stuff
  permission_handler: ^10.2.0
  # geolocator: ^9.0.2
  # geolocation: ^1.1.2
  # geocoder: ^0.2.1
  location: ^4.4.0
  get: ^4.6.5
  http: ^0.13.6
  #unique thingies
  mask_text_input_formatter: ^2.4.0
  uuid: ^3.0.7
  flutter_dotenv: ^5.1.0
  cached_network_image: ^3.3.0
  flutter_blurhash: ^0.7.0
  baseflow_plugin_template: ^2.1.2
  passwordfield: ^0.2.0
  email_validator: ^2.1.17
  jwt_decoder: ^2.0.1
flutter_icons:
  android: true
  ios: true
  # image_path: "assets/images/sharing_map-footprint-logo-whiteBg.png"
  cupertino_icons: ^0.1.2

dev_dependencies:
  flutter_test:
    sdk: flutter

flutter:
  # The following line ensures that the Material Icons font is
  # included with your application, so that you can use the icons in
  # the material Icons class.
  uses-material-design: true

  # To add assets to your application, add an assets section, like this:
  assets:
    - assets/images/
    # - assets/images/forest.jpg
    - assets/images/icons/
    - assets/images/cardImages/
    - assets/images/intro/
    - .env
  # An image asset can refer to one or more resolution-specific "variants", see
  # https://flutter.dev/assets-and-images/#resolution-aware.

  # For details regarding adding assets from package dependencies, see
  # https://flutter.dev/assets-and-images/#from-packages

  # To add custom fonts to your application, add a fonts section here,
  # in this "flutter" section. Each entry in this list should have a
  # "family" key with the font family name, and a "fonts" key with a
  # list giving the asset and other descriptors for the font. For
  # example:
  fonts:
    - family: Poppins
      fonts:
        - asset: assets/fonts/Poppins-Regular.ttf
  #       - asset: fonts/Schyler-Italic.ttf
  #         style: italic
  #   - family: Trajan Pro
  #     fonts:
  #       - asset: fonts/TrajanPro.ttf
  #       - asset: fonts/TrajanPro_Bold.ttf
  #         weight: 700
  #
  # For details regarding fonts from package dependencies,
  # see https://flutter.dev/custom-fonts/#from-packages
